name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking Changes"
    label: "💥 Breaking Change"

  - title: "🌟 New Features"
    label: "🌟 New Feature"

  - title: "⭐ Features"
    label: "⭐ Feature"

  - title: "🐞 Bug Fixes"
    label: "🐞 Bug Fix"

  - title: "🛠 Improvements"
    label: "🛠 Improvement"

  - title: "🌀 External Changes"
    label: "🔌 3rd Party Plugin"

  - title: "📖 Documentation"
    label: "📖 Docs"

  - title: "🌍 Localization"
    label: "🌍 i18n"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
